"""ScanSignal model for scanner-generated trading signals.

Implements Requirements: 9.1
"""

from datetime import datetime
from typing import Optional

from sqlalchemy import String, Float, Integer, Text, JSON, TIMESTAMP, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, validates, relationship

from src.database.base import Base


class ScanSignal(Base):
    """Scanner-generated trading signals awaiting user approval.

    Signals are generated by the scan engine, enriched with AI analysis,
    and presented to users with a countdown timer for approval/rejection.
    """

    __tablename__ = "scan_signals"

    # Primary key
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Foreign key to users
    user_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Signal details
    signal_type: Mapped[str] = mapped_column(String(50), nullable=False)
    symbol: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    confidence_score: Mapped[float] = mapped_column(Float, nullable=False)
    entry_price: Mapped[float] = mapped_column(Float, nullable=False)
    stop_loss: Mapped[float] = mapped_column(Float, nullable=False)
    target_price: Mapped[float] = mapped_column(Float, nullable=False)
    max_potential_loss: Mapped[float] = mapped_column(Float, nullable=False)

    # Status and countdown
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, server_default="pending", index=True
    )
    countdown_seconds: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="60"
    )
    expires_at: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP, nullable=True)

    # AI fields
    ai_quality_rating: Mapped[Optional[str]] = mapped_column(
        String(50), nullable=True
    )
    ai_warnings: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)
    ai_explanation: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Additional metadata
    metadata_json: Mapped[Optional[dict]] = mapped_column(
        "metadata", JSON, nullable=True
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP, nullable=False, server_default="NOW()"
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP, nullable=False, server_default="NOW()"
    )

    # Relationships
    user = relationship("User", back_populates="scan_signals")

    # --- Validators ---

    @validates("confidence_score")
    def validate_confidence_score(self, key: str, value: float) -> float:
        """Validate confidence score is between 50 and 100."""
        if value is None or value < 50 or value > 100:
            raise ValueError("Confidence score must be between 50 and 100")
        return value

    @validates("signal_type")
    def validate_signal_type(self, key: str, value: str) -> str:
        """Validate signal type is one of allowed values."""
        allowed = ("trend_pullback", "consolidation_breakout")
        if value not in allowed:
            raise ValueError(
                f"Signal type must be one of: {', '.join(allowed)}. Got: {value}"
            )
        return value

    @validates("status")
    def validate_status(self, key: str, value: str) -> str:
        """Validate status is one of allowed values."""
        allowed = ("pending", "approved", "rejected", "expired")
        if value not in allowed:
            raise ValueError(
                f"Status must be one of: {', '.join(allowed)}. Got: {value}"
            )
        return value

    @validates("entry_price")
    def validate_entry_price(self, key: str, value: float) -> float:
        """Validate that entry price is positive."""
        if value is None or value <= 0:
            raise ValueError("Entry price must be positive")
        return value

    @validates("stop_loss")
    def validate_stop_loss(self, key: str, value: float) -> float:
        """Validate that stop loss is positive."""
        if value is None or value <= 0:
            raise ValueError("Stop loss must be positive")
        return value

    @validates("target_price")
    def validate_target_price(self, key: str, value: float) -> float:
        """Validate that target price is positive."""
        if value is None or value <= 0:
            raise ValueError("Target price must be positive")
        return value

    def __repr__(self) -> str:
        return (
            f"<ScanSignal(id={self.id}, user_id={self.user_id}, "
            f"symbol='{self.symbol}', signal_type='{self.signal_type}', "
            f"confidence_score={self.confidence_score}, status='{self.status}')>"
        )
