"""
Execution layer data models for signals, trades, and order results.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Optional

from ..common.enums import SignalType


@dataclass
class Signal:
    """Represents a trading signal generated by an engine."""
    signal_type: SignalType
    engine: str  # 'trend' or 'mr'
    quantity: int
    reason: str
    timestamp: datetime
    price: float
    
    def __post_init__(self):
        """Validate signal data."""
        if self.quantity <= 0:
            raise ValueError(f"Invalid quantity: {self.quantity}")
        if self.price <= 0:
            raise ValueError(f"Invalid price: {self.price}")
        if self.engine not in ('trend', 'mr'):
            raise ValueError(f"Invalid engine: {self.engine}. Must be 'trend' or 'mr'")


@dataclass
class Trade:
    """Represents a completed trade."""
    timestamp: datetime
    quantity: int  # Positive for long, negative for short
    price: float
    trade_type: str  # 'trend' or 'mr'
    order_id: Optional[str] = None
    
    def __post_init__(self):
        """Validate trade data."""
        if self.quantity == 0:
            raise ValueError("Trade quantity cannot be zero")
        if self.price <= 0:
            raise ValueError(f"Invalid price: {self.price}")
        if self.trade_type not in ('trend', 'mr'):
            raise ValueError(f"Invalid trade_type: {self.trade_type}")
    
    @property
    def is_long(self) -> bool:
        """Check if trade is long."""
        return self.quantity > 0
    
    @property
    def is_short(self) -> bool:
        """Check if trade is short."""
        return self.quantity < 0


@dataclass
class MRTrade:
    """Represents an active mean reversion trade with tracking data."""
    entry_time: datetime
    entry_price: float
    quantity: int
    direction: str  # 'long' or 'short'
    impulse_start: float
    impulse_end: float
    candles_held: int = 0
    
    def __post_init__(self):
        """Validate MR trade data."""
        if self.quantity <= 0:
            raise ValueError(f"Invalid quantity: {self.quantity}")
        if self.entry_price <= 0:
            raise ValueError(f"Invalid entry_price: {self.entry_price}")
        if self.direction not in ('long', 'short'):
            raise ValueError(f"Invalid direction: {self.direction}. Must be 'long' or 'short'")
        if self.impulse_start <= 0 or self.impulse_end <= 0:
            raise ValueError("Impulse prices must be positive")
        if self.candles_held < 0:
            raise ValueError(f"Invalid candles_held: {self.candles_held}")
    
    def retracement_pct(self, current_price: float) -> float:
        """
        Calculate retracement percentage of the impulse move.
        
        Args:
            current_price: Current market price
            
        Returns:
            Retracement percentage (0-100+)
        """
        if current_price <= 0:
            raise ValueError(f"Invalid current_price: {current_price}")
        
        impulse_size = abs(self.impulse_end - self.impulse_start)
        if impulse_size == 0:
            return 0.0
        
        retracement = abs(current_price - self.impulse_end)
        return (retracement / impulse_size) * 100


@dataclass
class OrderResult:
    """Represents the result of an order execution."""
    order_id: str
    status: str  # 'PENDING', 'COMPLETE', 'REJECTED', 'CANCELLED'
    filled_quantity: int
    average_price: float
    message: str
    
    def __post_init__(self):
        """Validate order result data."""
        valid_statuses = ('PENDING', 'COMPLETE', 'REJECTED', 'CANCELLED')
        if self.status not in valid_statuses:
            raise ValueError(f"Invalid status: {self.status}. Must be one of {valid_statuses}")
        if self.filled_quantity < 0:
            raise ValueError(f"Invalid filled_quantity: {self.filled_quantity}")
        if self.average_price < 0:
            raise ValueError(f"Invalid average_price: {self.average_price}")
    
    @property
    def is_complete(self) -> bool:
        """Check if order is complete."""
        return self.status == 'COMPLETE'
    
    @property
    def is_rejected(self) -> bool:
        """Check if order was rejected."""
        return self.status == 'REJECTED'
    
    @property
    def is_pending(self) -> bool:
        """Check if order is pending."""
        return self.status == 'PENDING'
